spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: test-group-id
      auto-offset-reset: earliest

custom:
  kafka:
    topic: test-topic

datasource:
  url: jdbc:postgresql://localhost:5432/test_database
  username: your_username
  password: your_password
  driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO